Add dependency checking to manage

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -11,6 +11,14 @@ set -e
 
 function main() {
     if [ "$1" == "compile" ]; then
+        echo "Checking if cmake exists.."
+        set +e
+        command -v cmake
+        if [ $? != 0 ]; then
+            echo "cmake is required to compile this library."
+            exit 1
+        fi
+        set -e
         if [ ! -f ${CPWNTOOLS_DIR}/${EXTERN_LIBS_DIR}/tiny-bignum-c/bn.c ]; then
             git submodule update --init
         fi
@@ -51,10 +59,26 @@ function main() {
         git -C ${CPWNTOOLS_DIR} pull
         git submodule update --init
     elif [ "$1" == "clean" ]; then
-        make -C ${CPWNTOOLS_DIR}/build clean
+        echo "Checking if gmake exists..."
+        set +e
+        command -v gmake
+        if [ $? != 0 ]; then
+            echo "gmake is required to clean."
+            exit 1
+        fi
+        set -e
+        gmake -C ${CPWNTOOLS_DIR}/build clean
         rm -rf ${CPWNTOOLS_DIR}/html
         rm -rf ${CPWNTOOLS_DIR}/latex
     elif [ "$1" == "doc" ]; then
+        echo "Checking if doxygen exists..."
+        set +e
+        command -v doxygen
+        if [ $? != 0 ]; then
+            echo "doxygen is required to build documentation."
+            exit 1
+        fi
+        set -e
         doxygen ${CPWNTOOLS_DIR}/Doxyfile
     elif [ "$1" == "opendocs" ]; then
         ${CPWNTOOLS_DIR}/manage doc
@@ -76,6 +100,14 @@ function main() {
             exit 1
         fi
     elif [ "$1" == "format" ]; then
+        echo "Checking if clang-format exists..."
+        set +e
+        command -v clang-format
+        if [ $? != 0 ]; then
+            echo "clang-format is required to format the code."
+            exit 1
+        fi
+        set -e
         for i in ".h" ".c"; do
             for j in `find ${CPWNTOOLS_DIR}/src -name \*"${i}"`; do
                 echo "Formatting $j..."
